version: 2
builds:
  - skip: true
release:
  draft: true
  use_existing_draft: true
  mode: replace
changelog:
  sort: asc
  use: github
  format: "{{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }} <{{ .AuthorEmail }}>{{ end }})"
  groups:
    - title: Features
      regexp: "^.*(feat:|feat\\/|feat(\\([^\\)]*\\)):).*"
      order: 0
    - title: Bug Fixes
      regexp: "^.*(fix:|fix\\/|fix(\\([^\\)]*\\)):).*"
      order: 1
    - title: Docs
      regexp: "^.*(docs:|docs\\/|docs(\\([^\\)]*\\)):).*"
      order: 2
  filters:
    exclude:
      - "^ci"
      - "^test"
      - "^chore"
      - "^refactor"
      - "^style"
      - "^perf"
      - "^build"
      - "^revert"
      - "^deps"
