version: 2
builds:
  - skip: true
release:
  draft: true
  use_existing_draft: true
  mode: replace
  header: |
    ###### !!! REMOVE THIS HEADER BEFORE PUBLISHING !!!
    ## Release Checklist
    ### Draft Checklist
    - [ ] Tests from last nightly build have passed and are stable.
    - [ ] Release notes below have been reviewed and edited as needed.
    - [ ] Binaries/Archives/Packages.
      - [ ] Artifacts for each distro have been attached to the draft release
      - [ ] Any new artifact type is attached to the draft release (we filter on upload for expected file types)
    - [ ] Docker images for each distro have been published to ECR
    ### Publish Checklist
    - [ ] Checklist has been reviewed and all items are complete.
    - [ ] Draft header has been removed.
    - [ ] Docker images for each distro have been published to docker hub and tagged as latest
    - [ ] Slack notifications have been sent to appropriate channels
    - [ ] PR has been generated to update docs in [docs.newrelic.com](https://github.com/newrelic/docs-website/pulls)
    ###### !!! REMOVE THIS HEADER BEFORE PUBLISHING !!!
changelog:
  sort: asc
  use: github
  format: "{{ .Message }}"
  groups:
    - title: Features
      regexp: "^.*(feat:|feat\\/|feat(\\([^\\)]*\\)):).*"
      order: 0
    - title: Bug Fixes
      regexp: "^.*(fix:|fix\\/|fix(\\([^\\)]*\\)):).*"
      order: 1
    - title: Docs
      regexp: "^.*(docs:|docs\\/|docs(\\([^\\)]*\\)):).*"
      order: 2
  filters:
    exclude:
      - "^ci"
      - "^test"
      - "^chore"
      - "^refactor"
      - "^style"
      - "^perf"
      - "^build"
      - "^revert"
      - "^deps"
