.PHONY: ci
ci:
	act push -W .github/workflows/ci.yaml

ci_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act push -W .github/workflows/ci.yaml \
		--matrix distribution:nrdot-collector \
		--matrix fips:false

ci_custom_fips_matrix:
	@# repeat --matrix arg for multiple distros
	act push -W .github/workflows/ci-fips.yaml \
		--matrix distribution:nrdot-collector

ci_nightly_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act schedule -W .github/workflows/ci-nightly.yaml \
		--matrix distribution:nrdot-collector

ci_nightly_fips_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act schedule -W .github/workflows/ci-nightly-fips.yaml \
		--matrix distribution:nrdot-collector

ci_check_links:
	act push -W .github/workflows/check-links.yaml

ci_bump_component_version:
	act workflow_dispatch -W .github/workflows/ci-bump-component-versions.yaml

ci_bump_nrdot_version:
	act workflow_dispatch -W .github/workflows/release-bump-version-pr.yaml
