.PHONY: ci
ci:
	act push -W .github/workflows/ci.yaml

ci_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act push -W .github/workflows/ci.yaml \
		--matrix distribution:nrdot-collector-host

ci_nightly_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act schedule -W .github/workflows/ci-nightly.yaml \
		--matrix distribution:nrdot-collector-host

ci_e2e:
	act workflow_dispatch -W .github/workflows/ci-e2e.yaml