version: 2
project_name: nrdot-collector-releases-nightly
release:
  draft: true
  use_existing_draft: true
  disable: "true"
builds:
  - id: nrdot-collector
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: nrdot-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
  - id: nrdot-collector-fips
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: _build-fips
    binary: nrdot-collector-fips
    ldflags:
      - -w
      - -linkmode external
      - -extldflags '-static'
    tags:
      - netgo
    flags:
      - -trimpath
    env:
      - GOEXPERIMENT=boringcrypto
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
archives:
  - id: nrdot-collector
    ids:
      - nrdot-collector
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - src: config.yaml
nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" }}{{- else }}{{- .Arch }}{{- end }}{{- with .Arm }}v{{ . }}{{- end }}{{- with .Mips }}_{{ . }}{{- end }}{{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}'
    package_name: nrdot-collector
    contents:
      - src: nrdot-collector.service
        dst: /lib/systemd/system/nrdot-collector.service
      - src: nrdot-collector.conf
        dst: /etc/nrdot-collector/nrdot-collector.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    rpm:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    deb:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector
    ids:
      - nrdot-collector
    formats:
      - deb
      - rpm
    maintainer: New Relic <otelcomm-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector
    license: Apache 2.0
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" }}{{- else }}{{- .Arch }}{{- end }}{{- with .Arm }}v{{ . }}{{- end }}{{- with .Mips }}_{{ . }}{{- end }}{{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}'
    package_name: nrdot-collector-fips
    contents:
      - src: nrdot-collector-fips.service
        dst: /lib/systemd/system/nrdot-collector-fips.service
      - src: nrdot-collector-fips.conf
        dst: /etc/nrdot-collector-fips/nrdot-collector-fips.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector-fips/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    rpm:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    deb:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector-fips
    ids:
      - nrdot-collector-fips
    formats:
      - deb
      - rpm
    maintainer: New Relic <otelcomm-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector-fips
    license: Apache 2.0
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-amd64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-arm64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-arm64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-fips-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-fips-amd64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector-fips
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-fips-arm64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-fips-arm64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector-fips
    use: buildx
docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-arm64'
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:nightly'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-arm64'
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-fips'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-fips-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-nightly-fips-arm64'
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:nightly-fips'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-fips-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:nightly-fips-arm64'
blobs:
  - bucket: nr-releases
    provider: s3
    region: us-east-1
    directory: nrdot-collector-releases/nrdot-collector/nightly
  - bucket: nr-releases
    provider: s3
    region: us-east-1
    directory: nrdot-collector-releases/nrdot-collector-fips/nightly
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - --armor
      - ${artifact}
    signature: ${artifact}.asc
    artifacts: all
