version: 2
project_name: nrdot-collector-releases
release:
  draft: true
  use_existing_draft: true
  disable: "false"
builds:
  - id: nrdot-collector-k8s-fips
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: nrdot-collector-k8s-fips
    ldflags:
      - -w
      - -linkmode external
      - -extldflags '-static'
    tags:
      - netgo
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
      - GOEXPERIMENT=boringcrypto
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
archives:
  - id: nrdot-collector-k8s-fips
    ids:
      - nrdot-collector-k8s-fips
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: linux
        formats:
          - zip
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-k8s:{{ .Version }}-fips-amd64'
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector-k8s-fips
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-k8s:{{ .Version }}-fips-arm64'
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector-k8s-fips
    use: buildx
docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector-k8s:{{ .Version }}-fips'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-k8s:{{ .Version }}-fips-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector-k8s:{{ .Version }}-fips-arm64'
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - --armor
      - ${artifact}
    signature: ${artifact}.asc
    artifacts: all
