name: . 🐤 🦺 Canaries on demand

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
      previous_tag:
        description: 'Tag to compare to'
        required: true
      branch:
        description: 'Branch to test'
        required: false
        type: string
        default: "main"

jobs:
  canaries:
    uses: ./.github/workflows/component_canaries.yml
    with:
      TAG: ${{ inputs.tag }}
      PREVIOUS_TAG: ${{ inputs.previous_tag }}
      BRANCH_REF: ${{ inputs.branch }}
      PLATFORM: "linux"
      IMAGE: "cciutea768/nr-otel-collector" #should be changed after pre-release
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}

  alerts:
    needs: [canaries]
    uses: ./.github/workflows/component_canary_alerts.yml
    secrets:
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
      CANARIES_NR_API_KEY: ${{ secrets.CANARIES_NR_API_KEY }}
    with:
      TAG: ${{ inputs.tag }}
      NR_ACCOUNT_ID: 1038907
      NR_REGION: Staging
      INSTANCE_NAME_PATTERN: otel-canary:${{ inputs.tag }}-*
      TF_STATE_KEY: nr_otel_collector_prerelease_alerts/state_${{ inputs.tag }}
      TF_STATE_BUCKET: automation-pipeline-terraform-state
      TF_STATE_REGION: us-east-2
      POLICIES_PREFIX: "nr-otel-collector-pre-release__canaries_metric_comparator"
      REF: ${{ inputs.branch }}
