name: 🔄 CI | Nightly Helm Config Drift

on:
  schedule:
    # Dependency is external to this repo, so we need to check it regularly even if nothing changes
    # on our side
    ## Scheduled to run in the morning (PT) on every day-of-week from Monday through Friday.
    - cron: '0 15 * * 1-5'
jobs:
  k8s-config-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Sync k8s distro configs from helm chart
        run: |
          make -f ./distributions/nrdot-collector-k8s/Makefile check-k8s-configs
