name: Release

on:
  release:
    types:
      - released
    tags:
      - '*'

jobs:
  publishing-to-s3:
    name: Publish artifacts into s3 production bucket
    uses: ./.github/workflows/component_publish.yml

    secrets:
      DOCKER_HUB_ID: ${{ secrets.OHAI_DOCKER_HUB_ID }}
      DOCKER_HUB_PASSWORD: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_PRODUCTION }}
      AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION }}
    with:
      ACCESS_POINT_HOST: "production"
      SCHEMA_BRANCH: "main"
      RUN_ID: ${{ github.run_id }}
      TAG: ${{ github.event.release.tag_name }}
      AWS_S3_BUCKET_NAME: "nr-downloads-main"
      AWS_S3_LOCK_BUCKET_NAME: "onhost-ci-lock"
      ASSETS_TYPE: "all"

  release-docker:
    name: Release docker images

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set and validate distribution name and version
        run: .github/workflows/scripts/set_version.sh

      - name: Log into Docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password:  ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Publish docker manifest
        run: .github/workflows/scripts/docker_manifest_release.sh -i newrelic/nr-otel-collector -v ${{ env.NR_VERSION }}
