name: 🧩 CI Windows

on:
  workflow_call:
    secrets:
      nr_account_id:
        required: true
      nr_api_key:
        required: true
      nr_ingest_key:
        required: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          fetch-depth: 0 # required for tag metadata

      - name: Try to post random message to Event
        run: |
          # Define helper function for sending NR events
          function Send-NREvent {
              param([string]$Message)
              $accountId = "${{ secrets.nr_account_id }}"
              $event = @{
                  eventType = "NightlyLog"
                  platform = "windows-GitHub"
                  version = "2025"
                  message = $Message
              } | ConvertTo-Json -Compress
              newrelic events post --accountId $accountId --event $event
          }

          # Install newrelic cli (source: newrelic-cli readme doc)
          [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls'
          (New-Object System.Net.WebClient).DownloadFile(
            "https://download.newrelic.com/install/newrelic-cli/scripts/install.ps1",
            "$env:TEMP\install.ps1")
          & $env:TEMP\install.ps1
          # Refresh PATH to include newrelic-cli
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          # Set newrelic cli profile
          newrelic profiles add --profile test --accountId ${{ secrets.nr_account_id }} --apiKey ${{ secrets.nr_api_key }} --licenseKey ${{ secrets.nr_ingest_key }} -r us
          newrelic profiles default --profile test
          Send-NREvent "Basic sanity check"