name: . 💥 🐦 Canary alerts | delete

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of alerts to be destroyed'
        required: true

permissions:
  id-token: write

jobs:
  canary-alerts:
    uses: ./.github/workflows/component_canary_alerts_delete.yml
    secrets:
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
      CANARIES_NR_API_KEY: ${{ secrets.CANARIES_NR_API_KEY }}
    with:
      TAG: ${{ github.event.inputs.tag }}
      NR_ACCOUNT_ID: 11952800
      NR_REGION: Staging
      # To be decided 👇
      INSTANCE_NAME_PATTERN: canary:v${{ github.event.inputs.tag }}:*
      TF_STATE_KEY: nr_otel_collector_prerelease_alerts/state_${{ github.event.inputs.tag }}
      TF_STATE_BUCKET: automation-pipeline-terraform-state
      TF_STATE_REGION: us-east-2
      POLICIES_PREFIX: "nr-otel-collector-pre-release__canaries_metric_comparator"
      REF: "main"
