name: .. 🚧 🐈‍⬛ Snyk

on:
  workflow_call:
    secrets:
      slack_webhook:
        required: false
      snyk_token:
        required: true
    inputs:
      severity:
        required: true
        type: string

jobs:
  snyk:
    name: Scheduled Snyk scanner
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20.8'
          check-latest: true

      - name: build to generate go.mod
        run: make ci

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          args: --sarif-file-output=snyk-results.sarif --severity-threshold=${{ inputs.severity }} --all-projects

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: 'snyk-results.sarif'

      - name: Send notification to Slack Workflow
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": ":rotating_light: Hi CAOS (@hero), critical or high vulnerabilities found in NRDOT, see: https://github.com/newrelic/opentelemetry-collector-releases/security :rotating_light:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
