name: .. 🚧 🕵🏼 Trivy

on:
  workflow_call:
    secrets:
      slack_webhook:
        required: false
    inputs:
      image:
        required: false
        type: string
        description: "Image to scan with Trivy"
        default: "docker.io/newrelic/nr-otel-collector"
      tag:
        required: true
        type: string
      severity:
        required: true
        type: string

jobs:
  trivy_scanner:
    name: Trivy scanner for docker
    runs-on: ubuntu-22.04
    steps:
      - name: Sarif newrelic/nr-otel-collector
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          format: "sarif"
          output: "trivy-results.sarif"
          vuln-type: "os,library"
          severity: "${{ inputs.severity }}"
          exit-code: "1"
          ignore-unfixed: true
        env:
          # dbs are downloaded async in download_trivy_db.yml
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Print Trivy scan results # action can't do both table/sarif output, so we just print the sarif file
        if: ${{ (success() || failure()) && inputs.tag == 'latest' }}
        run: |
          if [[ -s trivy-results.sarif ]]; then
            cat trivy-results.sarif
          else
            echo "No sarif file found"
          fi
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        # Upload sarif only for latest
        if: ${{ (success() || failure()) && inputs.tag == 'latest' }}
        with:
          sarif_file: "trivy-results.sarif"

      - name: Send notification to Slack Workflow
        if: ${{ failure() && inputs.tag == 'latest' }}
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": ":rotating_light: Hi from your Github Action, vulnerabilities found in NRDOT, see: https://github.com/newrelic/opentelemetry-collector-releases/security :rotating_light:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
