name: .. 🚧 🕵🏼 Trivy

on:
  workflow_call:
    secrets:
      slack_webhook:
        required: false
    inputs:
      image:
        required: false
        type: string
        description: "Image to scan with Trivy"
        default: "docker.io/newrelic/nr-otel-collector"
      tag:
        required: true
        type: string
      severity:
        required: true
        type: string


jobs:
  trivy_scanner:
    name: Trivy scanner for docker
    runs-on: ubuntu-20.04
    if: ${{ ! github.event.schedule }} # Table output
    steps:
      - name: newrelic/nr-otel-collector
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: "${{ inputs.severity }}"

  trivy_scanner_scheduled:
    name: Scheduled Trivy scanner for docker
    runs-on: ubuntu-20.04
    if: ${{ github.event.schedule }} # Upload sarif when running periodically
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sarif newrelic/nr-otel-collector
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: "${{ inputs.severity }}"
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Send notification to Slack Workflow
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": ":rotating_light: Hi CAOS (@hero), critical or high vulnerabilities found in NRDOT, see: https://github.com/newrelic/opentelemetry-collector-releases/security :rotating_light:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
