name: 🚀 💾 Provision canaries

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_VPC_SUBNET:
        required: true

    inputs:
      TAG:
        required: true
        type: string
      PREVIOUS_TAG:
        required: true
        type: string
      PLATFORM:
        required: true
        type: string
      BRANCH_REF:
        required: false
        type: string
        default: "main"

env:
  TAG: ${{ inputs.TAG }}
  PREVIOUS_TAG: ${{ inputs.PREVIOUS_TAG }}
  PLATFORM: ${{ inputs.PLATFORM }}
  GITHUB_REFERENCE_NAME: ${{ inputs.BRANCH_REF }}
  IMAGE: ${{ inputs.IMAGE }}

permissions:
  id-token: write

jobs:
  infra:
    name: Prepare infra

    runs-on: ubuntu-20.04

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

#      - name: Destroy infra (cleanup)
#        uses: newrelic/fargate-runner-action@main
#        with:
#          aws_region: us-east-2
#          container_make_target: "test/provision-destroy TAG_OR_UNIQUE_NAME=canary:${{ env.TAG }}-${{ env.PLATFORM }}"
#          ecs_cluster_name: caos_otel_releases
#          task_definition_name: otel-releases-td
#          cloud_watch_logs_group_name: /ecs/test-prerelease-otel-releases
#          cloud_watch_logs_stream_name: ecs/test-otel-releases
#          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
#          repo_name: "newrelic/opentelemetry-collector-releases"
#          ref: "${{ env.GITHUB_REFERENCE_NAME }}"
#          log_filters: |
#            Destroy\scomplete!

      - name: Provision infra
        uses: newrelic/fargate-runner-action@main
        with:
          aws_region: us-east-2
          container_make_target: "test/provision-${{ env.PLATFORM }} TF_VAR_inventory_output=/srv/runner/inventory/${{ env.TAG }}-${{ env.PLATFORM }}-inventory.ec2 TAG_OR_UNIQUE_NAME=canary:${{ env.TAG }}-${{ env.PLATFORM }}"
          ecs_cluster_name: caos_otel_releases
          task_definition_name: otel-releases-td
          cloud_watch_logs_group_name: /ecs/test-prerelease-otel-releases
          cloud_watch_logs_stream_name: ecs/test-otel-releases
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: "newrelic/opentelemetry-collector-releases"
          ref: "${{ env.GITHUB_REFERENCE_NAME }}"
          log_filters: |
            \[ALLOW_MSG\].+
            TASK\s\[.*\]\s
            PLAY\s\[.*\]\s
            PLAY\sRECAP\s
            Apply\scomplete!
            ok=\d+\s+changed=\d+\s+unreachable=\d+\s+failed=\d+\s+skipped=\d+\s+rescued=\d+\s+ignored=\d+

      - name: Deploy OTEL for canaries
        uses: newrelic/fargate-runner-action@main
        with:
          aws_region: us-east-2
          container_make_target: "canaries PREVIOUS_IMAGE='${{ env.IMAGE }}:${{ env.PREVIOUS_TAG }}-rc' CURRENT_IMAGE='${{ env.IMAGE }}:${{ env.TAG }}-rc' ANSIBLE_INVENTORY='/srv/runner/inventory/${{ env.TAG }}-${{ env.PLATFORM }}-inventory.ec2' LIMIT=all"
          ecs_cluster_name: caos_otel_releases
          task_definition_name: otel-releases-td
          cloud_watch_logs_group_name: /ecs/test-prerelease-otel-releases
          cloud_watch_logs_stream_name: ecs/test-otel-releases
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: "newrelic/opentelemetry-collector-releases"
          ref: "${{ env.GITHUB_REFERENCE_NAME }}"
