name: 🔄 Lint | Renovate

on: pull_request

permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Renovate config validator
        run: npm install --global renovate

      - name: Test that the config is valid
        run: renovate-config-validator

      - name: Test that k8s test-spec is matched
        run: |
          # info log shows what files and dep ach 'manager' matched
          INFO_LOG=$(LOG_LEVEL=info renovate --platform=local)
          # we currently expect exactly 1 file and 1 dep
          if ! grep 'regex' <<< "${INFO_LOG}" | grep 'fileCount\": 1, \"depCount\": 1'; then
            echo "renovate didn't match k8s test-spec"
            DEBUG_LOG=$(LOG_LEVEL=debug renovate --platform=local)
            echo "Debug log:\n${DEBUG_LOG}"
            exit 1
          fi
