name: . 🚀 🐧 🦺 Otel packaging tests on demand

on:
  workflow_dispatch:
    inputs:
      unique_tag:
        description: 'Unique tag or prefix'
        required: true
      branch:
        description: 'Branch to test'
        required: false
        type: string
        default: "main"

jobs:
  packaging:
    uses: ./.github/workflows/component_provision_packaging.yml
    with:
      TAG_OR_UNIQUE_NAME: ${{ inputs.unique_tag }}
      BRANCH_REF: ${{ inputs.branch }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
