name: 📊 Report Metrics

on:
  workflow_dispatch:
  schedule:
    # Scheduled to run every 2 hours
    - cron: '0 */2 * * *'

jobs:
  downloads:
    name: Report GH Metrics
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      # Install Node 20
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 20
      - run: npm install @octokit/action
      - run: node .github/actions/gh-metrics.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.OTELCOMM_NR_INGEST_KEY }}
