name: . 🕵🏼 Security scanner
on:
  schedule:
    # Scheduled to run at 8 a.m on every day-of-week from Monday through Friday.
    - cron:  '0 8 * * 1-5'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to scan'
        required: false
        default: 'latest'

jobs:
  snyk:
    uses: ./.github/workflows/component_snyk.yml
    secrets:
      snyk_token: ${{ secrets.CAOS_SNYK_TOKEN }}
      slack_webhook: ${{ secrets.OTELCOMM_BOTS_SLACK_HOOK }}
    with:
      # minimum level is high
      severity: "high"
  docker-trivy:
    uses: ./.github/workflows/component_trivy.yml
    secrets:
      slack_webhook: ${{ secrets.OTELCOMM_BOTS_SLACK_HOOK }}
    with:
      tag: "${{ inputs.tag || 'latest' }}"
      severity: "CRITICAL,HIGH"
